name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Check Format
        run: |
          nix develop --command just format-check
      - name: Lint
        run: |
          nix develop --command just lint
      - name: Test
        run: |
          nix develop --command just test
      - name: Build
        run: |
          nix develop --command just build
